spring:
  application:
    name: client-bridge
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    jdbc:
      dialect: h2
    jpa:
      hibernate:
        ddl-auto: create
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: joaobertholino964@gmail.com
    password: jlig ougp egfv uxsb
    smtp:
        auth: true
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  webhook:
    callback: https://webhook.site/c9791efb-2e29-47e1-a553-c2e6f71d1b6e
  docker:
    compose:
      enabled: false